contact_links:
  - name: Support Request
    url: https://discuss.kubernetes.io
    about: |
      Please do not submit support requests or usage questions relating to Kustomize as issues. 
      Ask your question in the [Kubernetes Community Forums](https://discuss.kubernetes.io/), or in the #kustomize channel on [Kubernetes Slack](https://slack.k8s.io).
