name: Enhancement Tracking Issue
description: Request a minor enhancement to existing Kustomize functionality
labels: kind/feature
body:
- type: checkboxes
  attributes:
    label: Eschewed features
    description: Some features are out of scope for Kustomize because they are incompatible with its foundational design principles. Please review the [Eschewed Features](https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/) documentation before submitting your feature request.
    options:
      - label: This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.
        required: true

  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to have added?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
      
  - type: textarea
    id: current-alternatives
    attributes:
      label: Can you accomplish the motivating task without this feature, and if so, how?
    validations:
      required: true      
      
      
  - type: textarea
    id: design-alternatives
    attributes:
      label: What other solutions have you considered?
    validations:
      required: true        
